AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ArticleWordCloudAPI

  Sample SAM Template for ArticleWordCloudAPI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 500
  Api:
    Cors:
      AllowCredentials: False
      AllowHeaders: "'*'"
      AllowMethods: "'OPTIONS, POST, GET, PUT'"
      AllowOrigin: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  GetArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonS3FullAccess
      CodeUri: get_articles/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref ArticleTable
          UPDATE_ARTICLES_FUNCTION: !Ref UpdateArticlesFunction
      Events:
        GetArticles:
          Type: Api
          Properties:
            Path: /articles
            Method: get
  UpdateArticlesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      CodeUri: update_articles/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          ARTICLE_TABLE_NAME: !Ref ArticleTable
          API_REQUEST_TABLE_NAME: !Ref ApiRequestTable
          S3_BUCKET: !Ref WordCloudBucket
  ArticleTable:
    Type: AWS::Serverless::SimpleTable
  ApiRequestTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: time
        Type: Number
  WordCloudBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "PublicReadWrite"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - '*'



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
